### ISSUE TITLE
[WIP] Bundle Size Reduction: Move all kashi token images to temporary Github CDN

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#102]
Kashi currently utilizes lots of images from here: https://github.com/sushiswap/sushiswap-interface/tree/master/src/assets/kashi/tokens

**Comment by chillichelli** [comment]
Loading these images async reduces bundle size from 6.6mB to 6.1mB and DOMcontentLoaded stays around the same (~950ms).

![Schermafbeelding 2021-05-07 om 13 09 05](https://user-images.githubusercontent.com/80068137/117441299-71110380-af35-11eb-9e0d-4d31e98b129d.png)
Tbh we should create a placeholder token image that kinda flashes the way our logo has a flash on hover. Which designer do I contact for this?
