### ISSUE TITLE
Swap page styling issue on mobile

### ISSUE THREAD

**Issue by chillichelli** [sushiswap/sushiswap-interface#113]
Browser: ImToken
Styling issue when app.sushi.com/swap is displayed on an iPhone 12 pro.

![photo_2021-05-15_13-37-06](https://user-images.githubusercontent.com/80068137/118359306-202b8b80-b583-11eb-9dc1-57492475a6ea.jpg)

**Comment by chillichelli** [comment]
Need to get a physical device on AWS. I have no way of testing this.

**Comment by webeli** [comment]
PR: Fix for page styling issue on mobile #132
