### ISSUE TITLE
Rotating, Swipeable Announcements Banner

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#118]
**Operational Preface:**

Open a new branch when ready for review open a PR against Canary. Branch should be titled **announcements_banner** and mention this issue

The existing implementation can be found here: https://github.com/sushiswap/sushiswap-interface/blob/master/src/pages/Swap/index.tsx#L606

**Sample Design Page:**

<img width="600" alt="banner" src="https://user-images.githubusercontent.com/70670294/118759754-395c6280-b837-11eb-941f-33f064912294.png">

Currently there is only one announcement in the swap section. In order to allow for announcements the following enhancements should be made:
- allow for multiple banners
- banner should accept any jsx child element
- auto rotating
- keep current conditions (banner disappears when user performs a swap, this is already enabled)
- swipeable on mobile / draggable on desktop
- stretch: accessibility: on click on desktop user should be able to toggle with left right arrows
- stretch: possible dots on the bottom of or inside the banner indicating which banner is current and how many there are

**Comment by omakasebar** [comment]
@msilucifer if you could provide an update to this issue that would be appreciated! Thanks

**Comment by chillichelli** [comment]
If we were to go this route. Wouldn't it make sense to fetch content from the banners from some CMS? In figma we can just extract banners with text as an image right?

**Comment by omakasebar** [comment]
Hmm CMS would be cool - but we could just have it as static json/image. Which CMS should we use?

**Comment by chillichelli** [comment]
Yea that could also work. I don't really have much experience with CMS's but any headless cms would suffice

**Comment by msilucifer** [comment]
I am working on this issue now.

**Comment by Aveesh52** [comment]
Can I work on this issue?

**Comment by omakasebar** [comment]
@msilucifer mind giving an update? Or will reassign to @Aveesh52

**Comment by msilucifer** [comment]
No, I am working on this issue. I sent some DMs to you.

**Comment by omakasebar** [comment]
Please provide related updates in the issue. Thanks!

**Comment by msilucifer** [comment]
Okay
