### ISSUE TITLE
Remove UniswapV1 legacy code

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-interface#12]
We have no use for Uniswap legacy within this codebase, it adds unneeded complexity and acts as a distraction. Let's remove it!

**Comment by 0xVoltron** [comment]
@matthewlilley how do you identify what is a Uniswap legacy?

**Comment by omakasebar** [comment]
Resolved in https://github.com/sushiswap/sushiswap-interface/pull/94
