### ISSUE TITLE
Different supply APRs displayed on the same page

### ISSUE THREAD

**Issue by dangerousfood** [sushiswap/sushiswap-interface#127]
**Bug Description**
Two different supply APRs are being displayed

![image](https://user-images.githubusercontent.com/4099038/119036778-bf32f780-b976-11eb-930d-841ac8699533.png)

**Steps to Reproduce**
1. Navigate to https://app.sushi.com/bento/kashi/lend/0x418bc3ff0ba33ad64931160a91c92fa26b35acb0
2. Look at page
3. 
**Expected Behavior**
The same supply APR should be displayed

**Additional Context**
Firefox, Windows 10 😞

**Comment by omakasebar** [comment]
Thanks. This means the current and oracle exchange rates have diverged and the next individual to interact with this market should call updateExchangeRate if preferable. Will look into it a little more.

**Comment by omakasebar** [comment]
Deposited a bit of DAI, exchange rate should be similar now: https://app.sushi.com/bento/kashi/lend/0x418bc3ff0ba33ad64931160a91c92fa26b35acb0

**Comment by TopETH** [comment]
I started working on miso part, but I will try to fix this in my free time.

**Comment by matthewlilley** [comment]
AFAIK there's nothing to actually fix here, this is by design. I will confirm though.
