### ISSUE TITLE
Mockup: Token Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#128]
Operational Preface:

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled **mockup_token_page** and mention this issue

When submitting the PR please open a new folder under src/pages/Token and co-locate any relevant components within this folder as well.

Sample Design Page:

<img width="290" alt="token" src="https://user-images.githubusercontent.com/70670294/119047516-a2e98780-b983-11eb-8711-d7954a7480e9.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/n1Ifkyt7pIi1rIgMWMw6WA/Token-Page?node-id=45%3A1. If you are unable to access the Figma please reply in issue with an email address. The publicly viewable prototype can be found here: https://www.figma.com/proto/n1Ifkyt7pIi1rIgMWMw6WA/Token-Page?node-id=45%3A1

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks or external apis. Some guidance on how it should look on mobile can be found here: 
https://www.figma.com/file/n1Ifkyt7pIi1rIgMWMw6WA/Token-Page?node-id=38%3A89

For the charting component please use your discretion in selecting an appropriate library. Some common ones already used across various projects are the tradingView lightweight charts (https://github.com/tradingview/lightweight-charts) or Recharts (https://github.com/recharts/recharts)

Additionally you will need to update routing to reflect localhost:3000/token/:tokenId for the relevant screen found in the figma above. You do not need to implement the header as this exists currently on the project

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by webeli** [comment]
Will start working on this now.

**Comment by webeli** [comment]
Very close to finishing this one, still need some responsive work, will get that done soon :)

**Comment by webeli** [comment]
Since it was pretty messy to rebase the branch on canary, i've created a new branch with cherry-picking instead. PR: https://github.com/sushiswap/sushiswap-interface/pull/159
