### ISSUE TITLE
Connect Wallet bar appearing at top of screen on chrome mobile

### ISSUE THREAD

**Issue by JonahGroendal** [sushiswap/sushiswap-interface#135]
**Bug Description**
This only happens on canary.
When viewing on mobile using Chrome, the "connect wallet" bar appears at the top of the screen, covering the top bar and making the nav menu inaccessible. This only occurs on Chrome, on Firefox the bar is at the bottom of the screen as usual. I tested this on Android.

**Expected Behavior**
The "connect wallet" bar should appear at the bottom of the screen (unless it was purposefully changed?)

**Additional Context**
on chrome:
![image](https://user-images.githubusercontent.com/13501607/119194383-f70e6d80-ba50-11eb-909a-9cfc49d48af1.png)
on firefox:
![image](https://user-images.githubusercontent.com/13501607/119194431-0a213d80-ba51-11eb-93ba-c81f8266dd1e.png)

**Comment by chillichelli** [comment]
Is this still relevant @JonahGroendal ?

**Comment by JonahGroendal** [comment]
> Is this still relevant @JonahGroendal ?

I don't know. There isn't a pull request that mentions this issue so I assume it hasn't been fixed, but I would have to test it again to know for sure

**Comment by HYPRGK** [comment]
I've just tested this on a Pixel 4XL on Chrome, Chrome Beta, Chrome Dev and Chrome Canary and all of them show the "Connect to a wallet" banner at the bottom for me so I am unable to recreate the issue personally. Hope this helps!
