### ISSUE TITLE
Harvest button on SushiSwap Yield - MATIC - does not work 

### ISSUE THREAD

**Issue by Gondee** [sushiswap/sushiswap-interface#136]
**Bug Description**
I am using the ETH/USDT pool on Sushi Yield tab on MATIC. rewards show properly, but clicking the Harvest button does not seem to do anything. I tried 2 different RPC's but no luck. It seems that Meta Mask is not called and or does not generate the TX, leading me to believe its a api interaction issue.

**Steps to Reproduce**
1. sushi.com/yield on MATIC/Polygon
2. Click harvest for a pool you are farming in.
...

**Expected Behavior**
Expected to harvest your pending rewards. i.e generate a tx that performs the harvest. 

**Additional Context**

Here is the console log when clicking the button: 
![image](https://user-images.githubusercontent.com/5413555/119236307-54132d80-bafc-11eb-9501-59ff79bd37db.png)

Discussion around users with the issue on discord: 
https://discord.com/channels/748031363935895552/749850975581241374/845719364028203060

**Comment by omakasebar** [comment]
Seems like an RPC error, will investigate
<img width="1064" alt="rpc-error" src="https://user-images.githubusercontent.com/70670294/119236884-70649980-baff-11eb-9386-bc05bd94e028.png">

"Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'"

**Comment by omakasebar** [comment]
Issue with the rpc has been resolved. Thanks for everyone's patience!
