### ISSUE TITLE
Your SushiBar stats not loading

### ISSUE THREAD

**Issue by ilamalalatete** [sushiswap/sushiswap-interface#140]
**Bug Description**
User specific SushiBar stats not loading.

**Steps to Reproduce**
1. Go to `SushiBar (Main App)`
2. Click on `Your SushiBar stats`
3. Wait for loading to finish
4. See `unexpected error`

**Expected Behavior**
Should show user specific stats.

**Additional Context**
Some calls to the back-end are being returned with internal sever errors (status 500). See screencast.

https://user-images.githubusercontent.com/54866365/119259947-dcfb9900-bbd0-11eb-83a0-d8d706bcc27d.mp4

**Comment by omakasebar** [comment]
@ilamalalatete Hi, could you try to access this page on Chrome and let me know if you're still experiencing issues?

**Comment by ilamalalatete** [comment]
> @ilamalalatete Hi, could you try to access this page on Chrome and let me know if you're still experiencing issues?

Hi @omakasebar , I get the same error on all browsers I tested. That being Firefox, Chromium, Brave. I also deactivated all Extensions and Tracking-Blockers.

Calling the failing [URL](https://analytics.sushi.com/_next/data/c7kjMxgaSb4wRnEJw5_40/users/0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B.json) directly fails for me, even when using some command line tool like wget. Why would that API endpoint depend on the used browser?

If you think I can try something else, please feel free to tell me.

**Comment by omakasebar** [comment]
Seems to be working again: https://analytics.sushi.com/users/0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B
Calling the URL might not work since its graphQL on nextjs, the json is just an emulated artifact 

Resolved in https://github.com/sushiswap/sushiswap-analytics/commit/7755ca575a2fe165a832457734aef6ba7a842d34
