### ISSUE TITLE
[WIP] Path using chainId param

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#144]
Due to growing users on Polygon, it's becoming somewhat difficult to direct link items to that audience. For example we should be able to do something like:

https://app.sushi.com/#/swap?inputCurrency=0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270&outputCurrency=0x3a3df212b7aa91aa0402b9035b098891d276572b?chainId=137

where the interface immediately prompts the user to add and switch to polygon network. Not sure if this is best handled as a query param

**Comment by matthewlilley** [comment]
Yeah, should be able to prompt easily enough, and already setup to keep the state on change so that should be fine.

**Comment by wbnns** [comment]
@omakasebar Thanks for opening this issue; this would be very helpful to us as more networks continue to be supported on the platform. 👍

**Comment by matthewlilley** [comment]
closing until specific impl is ironed out and can be articulated
