### ISSUE TITLE
Internationalization Switch

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#17]
The code base currently uses react-i18next to handle internationalization
`import { useTranslation } from 'react-i18next'`

Translation constants are housed here: https://github.com/sushiswap/sushiswap-interface/tree/master/public/locales

The objective of this feature is to make a Language Selector in the Header to update the internationalization context.
Header component: https://github.com/sushiswap/sushiswap-interface/blob/master/src/components/Header/index.tsx

![i18n](https://user-images.githubusercontent.com/70670294/110031748-ea556580-7cfc-11eb-88d0-95fa6b91a477.jpg)

Please refer to the mockup above regarding implementation and reuse header subcomponents where possible. Please note on small mobile viewports internationalization switch may need to be hidden to prevent overflow.

**Comment by chillichelli** [comment]
Created a branch https://github.com/sushiswap/sushiswap-interface/tree/language_switch 
<img width="288" alt="Schermafbeelding 2021-03-05 om 00 08 34" src="https://user-images.githubusercontent.com/80068137/110043106-201f3c00-7d47-11eb-90ce-51ca78fc7cc6.png">

Is there a folder where we put common styled components? StyledMenuButton is defined 3 times now. If not, maybe we should consider doing so.

**Comment by omakasebar** [comment]
Feel free to create a new folder to house common styled components 👍

**Comment by omakasebar** [comment]
In the staging environment for this branch I'm seeing the following error. Just fyi
<img width="1391" alt="Screen Shot 2021-03-04 at 5 25 42 PM" src="https://user-images.githubusercontent.com/70670294/110044491-d74b9100-7d0e-11eb-809d-0e19deb11bbc.png">

**Comment by chillichelli** [comment]
I guess I should be using the staging env as well

**Comment by chillichelli** [comment]
I can't reproduce your error. Did you execute yarn install? I had to update two packages for it to work

**Comment by omakasebar** [comment]
Resolved, seems to be a yarn.lock issue
