### ISSUE TITLE
[Canary] Error on Lend: An unexpected error has occurred.

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#176]
Branch: Canary
URL: https://sushiswap-interface-canary.vercel.app/lend

**Comment by webeli** [comment]
@omakasebar i have a hard time reproducing this issue. 

- Which browser is being used?
- Are you connected to a wallet?
- Does the connected wallet lend out assets?

Any additional information would be helpful.

**Comment by matthewlilley** [comment]
Fixed
