### ISSUE TITLE
[Canary] Root is blank

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#177]
Branch: Canary
URL: https://sushiswap-interface-canary.vercel.app/

Page is blank, should default to swap page

**Comment by webeli** [comment]
@matthewlilley there's code that redirects `"/"` to `"/swap"` in `next.config.js`, but it's not beeing used. Are we going to do this in a different/better way or can we use this code.

We can use rewrites aswell:
https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by matthewlilley** [comment]
@webeli Yes, we'll stick with direct for now.
