### ISSUE TITLE
[Canary - Stylistic] Mobile Yield Farms

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#186]
Mobile Yield Farms could use some adjustments

<img width="486" alt="mobile" src="https://user-images.githubusercontent.com/70670294/122139400-c3c7c000-cdfd-11eb-94dd-29ff20f09a58.png">

Original:
<img width="351" alt="mobile-original" src="https://user-images.githubusercontent.com/70670294/122139509-fb366c80-cdfd-11eb-8708-b80edc530707.png">

**Comment by matthewlilley** [comment]
fixed
