### ISSUE TITLE
[Canary - Stylistic] Account Modal

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#190]
<img width="714" alt="account" src="https://user-images.githubusercontent.com/70670294/122141311-e9ef5f00-ce01-11eb-9a9a-0344f6d14589.png">

**Comment by matthewlilley** [comment]
FYI: This is about to be dropped, so probably no point actioning this.

**Comment by chillichelli** [comment]
I made this a bit more clear but will have to wait for design to create something proper
