### ISSUE TITLE
[Canary] Clicking Pool ( route: /add) on different network results in Error

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#191]
Reproduction: localhost:3001/add/ETH, switch to any secondary network (eg. Polygon), click "Pool"

<img width="1133" alt="Add" src="https://user-images.githubusercontent.com/70670294/122142943-3daf7780-ce05-11eb-927e-a52114f4a61c.png">

**Comment by matthewlilley** [comment]
Fixed
