### ISSUE TITLE
[Canary - Bug] useTradeExactIn doesn't work on canary and polygon

### ISSUE THREAD

**Issue by chillichelli** [sushiswap/sushiswap-interface#194]
![Schermafbeelding 2021-06-16 om 20 29 04](https://user-images.githubusercontent.com/80068137/122273268-889ebd00-cee1-11eb-9d59-b8a57ca780f9.png)

Above screenshot is from app.sushi.com and is what it is supposed to look like.
TradePrice is not showing for polygon network on canary branch.

![Schermafbeelding 2021-06-16 om 20 55 40](https://user-images.githubusercontent.com/80068137/122276596-3cee1280-cee5-11eb-8d77-f89536f85a28.png)

Issue seems to be related to useTradeExactIn hook inside the useDerivedSwapInfo

**Comment by 0xMasayoshi** [comment]
Looks like this error is being thrown in sushiswap-sdk in `wrappedAmount()` at https://github.com/sushiswap/sushiswap-sdk/blob/canary/src/entities/trade.ts#L92

The only `NATIVE` currency is ETH (see https://github.com/sushiswap/sushiswap-sdk/blob/canary/src/entities/currency.ts#L124) so the check fails on other networks.

**Comment by 0xMasayoshi** [comment]
Fixed in the latest SDK update
