### ISSUE TITLE
feature request: Enable users to share links of pairs that are not on Ethereum mainnet

### ISSUE THREAD

**Issue by erwanor** [sushiswap/sushiswap-interface#217]
Hi team,

**Is your feature request related to a problem? Please describe.**
I want to share a link to a pair that is not on Ethereum Mainnet.

**Describe the solution you'd like**
Enable users to specify a custom `chainId` parameter

`https://app.sushi.com/swap#/swap?inputCurrency=0x7ceb23fd6bc0add59e62ac25578270cff1b9f619&outputCurrency=0xede1b77c0ccc45bfa949636757cd2ca7ef30137f&network=0xpolygon`

Emphasis to the last parameter in this URL: `network=0xpolygon`

**Describe alternatives you've considered**
In the interest of getting this out as fast as possible, I think Sushi could host alternative front-ends that default to popular networks.

For example, for 0xPolygon you would have a front-end instance running at:
`https://polygon.sushi.com/swap` with default `chainId = 137`

AFAIK, this is easily implemented by modifying the default `chainId`: https://github.com/sushiswap/sushiswap-interface/blob/canary/src/connectors/index.ts#L41

**Comment by matthewlilley** [comment]
@erwanor It's possible that we host different frontends, or that we dynamically set the default chainId depending on the network the user is on, the latter was the plan. Feel free to open a PR, this has been planned for a while. You can test with subdomains arbitrum.sushi.com, and others which are already setup if you wish.

**Comment by matthewlilley** [comment]
@erwanor possible now, but still considering hosting multiple which defualt to specific networks, the trouble is that MetaMask will not trust each domain, so if you connect on subdomainA you will need to reconnect on subdomainB, so this is probably a reason not to.
