### ISSUE TITLE
Farm view Max button to unstake not working

### ISSUE THREAD

**Issue by Severino** [sushiswap/sushiswap-interface#221]
**Bug Description**
When unstaking in a farm. The max button is not working.

**Steps to Reproduce**
1. (If not already) Stake in a farm (e.g. on Harmony ONE/1WBTC here the LP is super small and max is a necessitty to work)
2. In the unstake try to use the max button to unstake.

**Expected Behavior**
Fill the form with the total staked LP amount.

**Additional Context**
Occured on Google Chrome (Version 91.0.4472.124)

**Comment by 0xMasayoshi** [comment]
Looks like its being covered up by the notification popup component, which actually causes a portion of the the entire screen to be unclickable.

<img width="863" alt="Screen Shot 2021-07-18 at 1 53 48 PM" src="https://user-images.githubusercontent.com/82962873/126077420-0ee584ee-8132-4227-b70f-f782d74314a3.png">

One fix is to remove the full height property of the component (see #222)
