### ISSUE TITLE
Tokens list being covered by popular tokens

### ISSUE THREAD

**Issue by b70v** [sushiswap/sushiswap-interface#232]
**Bug Description**
The popular tokens in the token selection page covers the rest of the selection page on smaller devices. My display size is 4.7 inches.

**Steps to Reproduce**
1. Go to the main page.
2. Click on the select token button

**Expected Behavior**
The list of all tokens should be more visible. It does not move when scrolling through the tokens. Pinning it to the top would probably fix this.

**Additional Context**
Here’s a picture of the issue:

![CE3CC635-C351-4C6E-9132-3554C67D6768](https://user-images.githubusercontent.com/71076915/126205222-94280f19-7f53-43b0-84d7-4cf4c2923c03.png)

**Comment by TopETH** [comment]
This issue is resolved and the PR is merged into canary branch.
