### ISSUE TITLE
[REFACTOR] use of BoringHelper for Bento Balances in favor of Multicall 

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-interface#279]
BoringHelper will often fail and cause the entire balances page to explode. This needs to be refactored out in favor of a pure multicall implementation to avoid this in future, and allow for better flexibility.

**Comment by sambacha** [comment]
What you think about this?

https://github.com/manifoldfinance/sushicall/blob/master/contracts/Sushicall.sol
