### ISSUE TITLE
[REFACTOR] react-tabs -> headless-ui tabs

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-interface#289]
Refactor use of react-tabs to headless-ui tabs and drop this dependency.

**Comment by Jds-23** [comment]
hey @matthewlilley ,
I can help with Refactor use of react-tabs to headless-ui tabs. This would be a good starting point for me to start contributing. 😁

**Comment by matthewlilley** [comment]
@Jds-23 sounds good to me!

**Comment by Jds-23** [comment]
Would you assign it me then. I will start.

**Comment by matthewlilley** [comment]
> Would you assign it me then. I will start.

You've got it.

**Comment by Jds-23** [comment]
Hey @matthewlilley , some help. I have cloned the repo and installed all the dependencies. Is there any step I am missing for setup of the development enviroment.

**Comment by Jds-23** [comment]
Hey @matthewlilley ,  I facing this issue while running the app. 
It will great if you point out what I am missing.
![Screenshot (144)](https://user-images.githubusercontent.com/67229156/129708517-646ae4f1-7789-473e-8c13-c77531574d3a.png)
![Screenshot (145)](https://user-images.githubusercontent.com/67229156/129708552-61d67f09-6c3a-4b69-899e-c47856c9ab9e.png)

**Comment by matthewlilley** [comment]
> Hey @matthewlilley , I facing this issue while running the app.
> It will great if you point out what I am missing.
> ![Screenshot (144)](https://user-images.githubusercontent.com/67229156/129708517-646ae4f1-7789-473e-8c13-c77531574d3a.png)
> ![Screenshot (145)](https://user-images.githubusercontent.com/67229156/129708552-61d67f09-6c3a-4b69-899e-c47856c9ab9e.png)

Hey, are you having issues with latest canary? I can see builds are successful there.

**Comment by Jds-23** [comment]
Not sure. Should I follow the instructions DEVELOPMENT.md ?

**Comment by matthewlilley** [comment]
> Not sure. Should I follow the instructions DEVELOPMENT.md ?

To get started you should be able to do this one liner.

```sh
git clone https://github.com/sushiswap/sushiswap-interface.git && cd sushiswap-interface && yarn && yarn dev
```

**Comment by Jds-23** [comment]
> > Not sure. Should I follow the instructions DEVELOPMENT.md ?
> 
> To get started you should be able to do this one liner.
> 
> ```shell
> git clone https://github.com/sushiswap/sushiswap-interface.git && cd sushiswap-interface && yarn && yarn dev
> ```

Thanks @matthewlilley  it finally worked.
