### ISSUE TITLE
[REFACTOR] uses of styled-components -> tailwind

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/sushiswap-interface#290]
Majority of work has been done here and very few usages reaming at this point.

![Screenshot_120](https://user-images.githubusercontent.com/6063350/129498841-35f65d57-c2f7-4fe3-af21-d335b50521a7.png)

**Comment by Jds-23** [comment]
Hey @matthewlilley , I would like to take this up.

**Comment by Jds-23** [comment]
Hey @matthewlilley , should I take this up?

**Comment by Jds-23** [comment]
Hey @matthewlilley , can I work on this?

**Comment by Jds-23** [comment]
@tmlee @pascalvanhecke @dy

**Comment by Jds-23** [comment]
hey @matthewlilley 
![Screenshot (157)](https://user-images.githubusercontent.com/67229156/132113552-7ebe64a2-d41c-47e9-96f9-9ac6e7f63f56.png)
How should i fix this?

**Comment by Jds-23** [comment]
Got it working! 😁 @matthewlilley used the suggestion you gave before.
