### ISSUE TITLE
Integrate SUSHI - xSUSHI 1-click (SushiBar app) into Swap app? 

### ISSUE THREAD

**Issue by Ro5s** [sushiswap/sushiswap-interface#32]
Similar to how [Swap app](https://app.sushi.com/swap) calls wETH contract for swaps between ETH and wETH, it seems efficient to have SUSHI <-> xSUSHI `enter()` + `leave()`  in Swap UI (.... users might be unfamiliar with [SushiBar app](https://app.sushi.com/farms/xsushi), or o/wise don't want to switch contexts). **Edit: duplicative cost of approving swap router and sushibar to spend sushi token could cut against ux. For folks already on ‘guest list’ of sushi bar through prior approval, seems useful.

**Comment by omakasebar** [comment]
There's a simple interface on exchange: https://exchange.sushi.com/#/stake, I'll make a new tab on the app.sushi.com interface with the same functionality

**Comment by Ro5s** [comment]
awesome :~) closing this issue as resolved
