### ISSUE TITLE
Missing Dependencies (cids, multicodec, multihashes)

### ISSUE THREAD

**Issue by prodvdjin** [sushiswap/sushiswap-interface#324]
**To run sushiswap on local, need to install missing dependencies**

npm i --save cids multicodec multihashes

**Comment by AyuOKExChain** [comment]
> **要在本地运行sushiswap，需要安装缺少的依赖项**
> 
> npm i --save cids multicodec multihashes

yarn 
yarn build
yarn dev

node version = 14.7.5 
OK?😁
