### ISSUE TITLE
Incorrect Information Shown on xDai Token Pairs Pages

### ISSUE THREAD

**Issue by JHGrove3** [sushiswap/sushiswap-interface#326]
**Bug Description**
Information about Volume (24h), Fees (24h), Avg. Trade (24h), and Utilisation (24h) is incorrect for token pairs on the xDai network.

**Steps to Reproduce**
I have selected a token pair at random for this example. I'm using HAUS-WXDAI

1. Open the token pair page:
https://analytics-xdai.sushi.com/pairs/0xb59da143ba3197dd5ea3844f429d37a1c2b1afd8

2. Open the All Pairs Analytics page:
https://analytics-xdai.sushi.com/pairs

3. Go to page 2 of the All Pairs Analytics list, where HAUS-WXDAI is shown.

4. Compare the data shown on the All Pairs list with data on a specific pair page.  You will see that there are a number of inconsistencies in the data.  On some pages, for example, the data for the last 7 days is shown where it says it's data from the last 24 hours.

In the attached screenshot of the HAUS-WXDAI pair, I've highlighted incorrect information with red rectangles, and correct information with green rectangles.

It's possible that the information on the All Pairs list is correct and the information on the token pair page is wrong. But either way, someone should determine why the incorrect information is being shown at all and why the pages are not consistent.

**Expected Behavior**
The data should match between the two pages. It's the same data, after all.

![Pairs List](https://user-images.githubusercontent.com/2583972/131898202-d37777d7-48e4-48b7-8507-02f7e217dc99.png)

![Pair Analytics](https://user-images.githubusercontent.com/2583972/131898236-a966cac4-b406-496f-ab7a-e23377667a26.png)

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by JHGrove3** [comment]
Additional Information:
When looking at the individual token page, there are also data inconsistencies.

It looks like perhaps its the Volume (24h) and Fees (24h) that are wrong in this case, and perhaps the 7d volume and fees might be correct.  But I can't tell that just by looking.

![Token Page](https://user-images.githubusercontent.com/2583972/131902643-6f61d0ca-c45a-436d-b60f-c07d8fc9e181.png)

**Comment by JHGrove3** [comment]
The more I look at the pair information page, the more unsettled I get. I'm realizing that I have no way of knowing whether the graphs or the data tables are correct.

The information about fees (24h) is one of the most important metrics, and it's simply wrong. It seems to be reporting the 7d fees instead, and calling them 24h fees, which is erroneously overstating the returns by a factor of 7x.

The information about volume (24h) is also very important, and that is wrong, too.

I think the fix for this should be quite simple -- just review the API and make sure you are mapping the correct data to the correct table labels on the page.

But until the fix is made, this page is worse than useless, because it's causing people to make bad investment decisions based on erroneous data.

**Comment by Jds-23** [comment]
I believe the fix on these will be simple, I would like to take this up.😀

**Comment by matthewlilley** [comment]
Thanks for flagging this up, the app itself is being depreciated shortly, however I doubt this is an issue with the app but rather the data feeds it consumes. I flagged this one up to be checked over as I noticed various issues with the data also.
 
 https://thegraph.com/legacy-explorer/subgraph/sushiswap/xdai-exchange

**Comment by matthewlilley** [comment]
"The data should match between the two pages. It's the same data, after all." - Actually the data is different. The difference is rolling 24h data, vs daily buckets which are reset from 00:00. This has been a common complaint and source of confusion, but has been resolved in upcoming integrated version.

**Comment by Jds-23** [comment]
So @matthewlilley , so the frontend is fine?

**Comment by JHGrove3** [comment]
What about things like the Volume number being shown in the fees column?  
(See the image in the first comment:)
https://github.com/sushiswap/sushiswap-interface/issues/326#issuecomment-911978160
