### ISSUE TITLE
Breaks when clicked on Read More about an Unsupported Asset

### ISSUE THREAD

**Issue by Jds-23** [sushiswap/sushiswap-interface#332]
**Bug Description**
When you add an Unsupported token in Sushiswap. It shows this screen.
![Screenshot (176)](https://user-images.githubusercontent.com/67229156/132446727-bfdaca54-114e-4b84-90d5-dceb776493e7.png)

When Clicking on Read More About Unsupported Asset. It breaks.
![image](https://user-images.githubusercontent.com/67229156/132446909-2380e4a0-a783-45a8-bf0c-0babbcff0b6d.png)

**Steps to Reproduce**
1. Go to https://app.sushi.com/swap
2. Click on Select Token Dropdown
3. Paste Address 0x4922a015c4407F87432B179bb209e125432E4a2A
4. Import It. 
...

**Expected Behavior**
The Expected Behavior, is to show a Modal containing Info about Unsupported Assets.

![image](https://user-images.githubusercontent.com/67229156/132447381-9790e3f4-5732-4261-86ad-a7cf1c6ea17e.png)

**Comment by matthewlilley** [comment]
Thanks for flagging this.
