### ISSUE TITLE
Ability to disconnect account

### ISSUE THREAD

**Issue by NotEternal** [sushiswap/sushiswap-interface#351]
Add a new button somewhere in this modal. I suppose it's better to be able to disconnect an external walllet inside the app

![image](https://user-images.githubusercontent.com/61930014/134175772-26e1f84d-e942-4c35-ae5e-f1c560a05504.png)

**Comment by Jds-23** [comment]
@matthewlilley should I work on this?

**Comment by Jds-23** [comment]
@chillichelli should I work on this?

**Comment by colinnielsen** [comment]
Hey @matthewlilley I've got a real easy fix for this working, I can create a PR at any time

**Comment by chillichelli** [comment]
Fixed on canary
