### ISSUE TITLE
"Waiting for Confirmation" modal stays indefinitely in the mobile UI when using WalletConnect + Valora

### ISSUE THREAD

**Issue by jeanregisser** [sushiswap/sushiswap-interface#444]
Hey Sushi team, I'm here to report a bug.

The "Waiting for Confirmation" modal stays indefinitely in the mobile UI of Sushi when using WalletConnect + Valora on the Celo blockchain. See the video.

https://user-images.githubusercontent.com/57791/142439768-a464c033-dadd-4eaa-922e-0a41bc3e5d84.mp4

Here are the steps to reproduce:
1. Open https://app.sushi.com in Safari on iOS
2. Connect Valora using WalletConnect
3. Initiate a swap (for instance cUSD -> cEUR)
4. Allow the transaction in Valora
5. Go back to Safari
6. Sushi remains on the "Waiting for Confirmation" modal indefinitely. Though the actual swap has been processed onchain successfully.

This is reproducible on iOS Safari (iOS 14 and 15.1).
It happens also with Chrome on Android.

However there is NO issue when doing the same between a desktop browser (Safari or Chrome) and Valora by scanning the WalletConnect QR code.

 Let me know if you have any question.

**Comment by jeanregisser** [comment]
Update, today the confirmation modal now remains on desktop too.

**Comment by jeanregisser** [comment]
This is still an issue.

**Comment by jeanregisser** [comment]
And still an issue today.

**Comment by jiro-ono** [comment]
![2022-03-03 16 46 04](https://user-images.githubusercontent.com/70732637/156677817-413f7f83-bf8f-4d38-913c-064c2527af89.jpg)

Also Jean reported that WalletConnect session doesn't provide app name anymore when connecting
