### ISSUE TITLE
Bug report: Borrow page fails to render due to CORS error

### ISSUE THREAD

**Issue by ctjlewis** [sushiswap/sushiswap-interface#449]
### Description
The SushiSwap interface tries to load a token list from `tryroll.com`, but that application does not have the necessary CORS headers to allow you to fetch that resource from this domain. Thus, the Borrow view does not display anything.

![image](https://user-images.githubusercontent.com/1657236/142738628-2c067657-ee29-41fb-b688-3e10c7a7141e.png)

#### Location
https://app.sushi.com/borrow

#### Error
```
Access to fetch at 'https://app.tryroll.com/tokens.json' from origin 'https://app.sushi.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Fix
You can use `fetch(..., { mode: 'no-cors' })` to fetch the resource without CORS.

Alternatively the tryroll.com administrators and ask them to add the CORS headers, or ensure the token lists are bundled at build-time.  You can also use [Next's `getStaticProps(){}` method](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) to fetch the resource on the server and pass it into the component as a prop.

I recommend using `getStaticProps(){}` to load the data on the server with `fetch(..., { mode: 'no-cors' })`. This will make the client experience better by not forcing them to load and parse the resource directly.

**Comment by ctjlewis** [comment]
I would submit a PR but I'm having trouble developing locally, get the following error from Alchemy:

```
[{"jsonrpc": "2.0", "id": 14, "error": {"code": -32600, "message": "Origin \"localhost\" is not on whitelist."}}]
```

**Comment by matthewlilley** [comment]
@ctjlewis In the rpcs config you will have to add your own alchemy key to rid this error when not connected with a wallet
