### ISSUE TITLE
Bug Report: Changing to Avalanche chain is broken

### ISSUE THREAD

**Issue by Jds-23** [sushiswap/sushiswap-interface#453]
![image](https://user-images.githubusercontent.com/67229156/143728632-7b119ef8-d924-485c-a682-b2b07571d94d.png)
![image](https://user-images.githubusercontent.com/67229156/143728633-cb0d0768-9a00-4147-b7c3-11e309edb8cf.png)
![image](https://user-images.githubusercontent.com/67229156/143728634-ec5f633e-9a43-47ef-9902-e7417d2d19cd.png)

I will be submitting a pull request that will be fixing this issue.

**Comment by matthewlilley** [comment]
Thanks @Jds-23, there's an issue with web3-react which was hotfixed for now
