### ISSUE TITLE
Wallet Connect Liquidity Pool Fails on Polygon

### ISSUE THREAD

**Issue by dougransom** [sushiswap/sushiswap-interface#582]
Connect  a WalletConnect to sushiswap on polygon network.  Attempt to add MATIC/WETH Liquidity. The Approve Button doesn't respond to mouse clicks.

![image](https://user-images.githubusercontent.com/3534162/152187668-546744ec-f9c1-4b5d-87f9-648ee5499c53.png)

**Comment by sambacha** [comment]
this should be fixed sometime today
