### ISSUE TITLE
Change chart timeframe

### ISSUE THREAD

**Issue by gasperbr** [sushiswap/sushiswap-interface#599]
Get rid of the weekly time frame on these charts since it only has 7 data points. Use 1y by default  https://app.sushi.com/analytics/dashboard
https://app.sushi.com/analytics/tokens/0x...
![image](https://user-images.githubusercontent.com/42702599/152664056-c9f45691-aa57-4a48-ac1f-a8f945b1ced7.png)
vs
![image](https://user-images.githubusercontent.com/42702599/152664063-d1e34a47-1e71-48b1-9591-1132e7ddc82f.png)

Replace the 1w option with 6m

**Comment by matthewlilley** [comment]
defaulting to 1m for now, the charts need redoing since they don't scale well on high resolution
