### ISSUE TITLE
Restyle: Add Liquidity Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#60]
**Operational Preface:**

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled restyle_addLiquidity and mention this issue
The current implementation can be found at: https://sushiswap-interface-git-canary-teamsushi.vercel.app/add/ETH
The current page directory can be found at: https://github.com/sushiswap/sushiswap-interface/tree/master/src/pages/AddLiquidity
Related existing components and layout (for the swap page) can be found at:https://github.com/sushiswap/sushiswap-interface/tree/master/src/pages/Swap 

----------------------------------------

**Sample Design Component:**
<img width="415" alt="addLiquidity" src="https://user-images.githubusercontent.com/70670294/116490038-0f2d0b80-a85c-11eb-83f2-2c49b60e476c.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/yWJykiIb4TkV6zbLpItPDv/Exchange?node-id=37%3A857. If you are unable to access please reply in issue with a email address, additionally the public prototype can also be viewed here: https://www.figma.com/proto/zibFzATC7X8UEdkGMRPllo/Staking?scaling=min-zoom&page-id=51%3A86&node-id=51%3A87

Implement the following pages based on the design above. The page is expected to be fully functional and tested on ropsten/kovan before opening a PR. Existing page provides the relevant hooks and the swap page already demonstrates a similar implementation.

You are not expected to implement the gas tracker or wallet icon, please use the existing component from the swap

**Comment by TopETH** [comment]
Is this just restyle or need to implement web3 logic?
For example, the bottom component isn't in original page. (which includes your pool balance, your pool share, liquidity provider fee and network fee).
So if I make this component, do I need to fetch all those information and show correct value? or just placeholders?

**Comment by matthewlilley** [comment]
Hey @TopETH,

Just a static mock-up based on the designs will be fine for now.

**Comment by omakasebar** [comment]
Both Merged!
