### ISSUE TITLE
Mockup: Transactions Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#61]
**Operational Preface:**

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled mockup_transactions and mention this issue
_When submitting the PR please open a new folder under src/pages titled Transactions and co-locate any relevant components within this folder as well._ 

----------------------------------------

**Sample Design Page:**
<img width="733" alt="Transactions" src="https://user-images.githubusercontent.com/70670294/116515718-44545080-a892-11eb-9933-a3184801e3c4.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/yWJykiIb4TkV6zbLpItPDv/Exchange?node-id=41%3A799. If you are unable to access please reply in issue with a email address

Implement the following page based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks.

Additionally you will need to update routing to reflect localhost:3000/transactions for the relevant screens found in the figma above. You do not need to implement the header as this exists currently on the canary branch

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by webeli** [comment]
I've started working on this one :)

**Comment by omakasebar** [comment]
Great, thank you for the update and tagging the issue

**Comment by omakasebar** [comment]
Merged- great job!
