### ISSUE TITLE
Mockup: Onsen AMA

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#62]
**Operational Preface:**

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled mockup_onsen_ama and mention this issue

_When submitting the PR please open a new folder under src/pages/Onsen titled Ama and co-locate any relevant components within this folder as well._ 

----------------------------------------

**Sample Design Page:**

<img width="723" alt="OnsenAma" src="https://user-images.githubusercontent.com/70670294/116516482-44a11b80-a893-11eb-8392-a65e3763cd50.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/miPg1AqEDC8ae6WMVEzJPx/Onsen?node-id=158%3A308. If you are unable to access please reply in issue with a email address, additionally the public prototype can also be viewed here: https://www.figma.com/proto/miPg1AqEDC8ae6WMVEzJPx/Onsen?node-id=158%3A308&scaling=min-zoom&page-id=155%3A154

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks or external apis. Also you are not expected to implement the background wave pattern displayed in the design. 

Additionally you will need to update routing to reflect localhost:3000/onsen/ama for the relevant screen found in the figma above. You do not need to implement the header as this exists currently on the project

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by kingdayx** [comment]
Please assign me to this one I am going to work on this one first. Thanks!

**Comment by omakasebar** [comment]
Hi @kingdayx if you could provide an update on this issue by tomorrow, if not it will be open for reassignment. Thank you!

**Comment by ironsoul0** [comment]
I would be happy to help on this one if the issue will be reopened

> Hi @kingdayx if you could provide an update on this issue by tomorrow, if not it will be open for reassignment. Thank you!

**Comment by kingdayx** [comment]
also the wavy background

**Comment by omakasebar** [comment]
@kingdayx any updates to this? If not update on this I will reassign tomorrow - thanks

**Comment by omakasebar** [comment]
Thanks @JonahGroendal

**Comment by JonahGroendal** [comment]
@omakasebar a couple questions:
1. Should I implement all the pages in the linked figma or only the "AMA Series" page (the one shown in this issue's picture)?
2. I don't see any figma mockups for how these pages should look on mobile. Should I do my best to make them responsive or just make them for desktop for now?

**Comment by omakasebar** [comment]
> @omakasebar a couple questions:
> 
> 1. Should I implement all the pages in the linked figma or only the "AMA Series" page (the one shown in this issue's picture)?
> 2. I don't see any figma mockups for how these pages should look on mobile. Should I do my best to make them responsive or just make them for desktop for now?

Hey @JonahGroendal 
1. only the "AMA Series" page for now
2. Yes unfortunately no figma mockups for mobile - try your best to make them reasonably responsive with tailwind breakpoints and then we can review
