### ISSUE TITLE
Mockup: Onsen Yield Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#63]
**Operational Preface:**

Open a new branch when ready for review open a PR against **Canary**. Branch should be titled mockup_onsen_yield and mention this issue

_When submitting the PR please open a new folder under src/pages/Onsen titled Yield and co-locate any relevant components within this folder as well._ 

----------------------------------------

**Sample Design Page:**

<img width="731" alt="OnsenYield" src="https://user-images.githubusercontent.com/70670294/116519475-23422e80-a897-11eb-9615-135cc33c19cb.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/miPg1AqEDC8ae6WMVEzJPx/Onsen?node-id=155%3A155. If you are unable to access the Figma please reply in issue with an email address. The publicly viewable prototype can be found here: https://www.figma.com/proto/miPg1AqEDC8ae6WMVEzJPx/Onsen?node-id=155%3A155&scaling=min-zoom&page-id=155%3A154

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks or external apis. Also you are not expected to implement the background wave pattern displayed in the design. 

Additionally you will need to update routing to reflect localhost:3000/onsen/yield for the relevant screen found in the figma above. You do not need to implement the header as this exists currently on the project

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by kingdayx** [comment]
I just started working on this!

**Comment by webeli** [comment]
Hi @kingdayx do you need any help on this one?

**Comment by kingdayx** [comment]
0xMasayoshi which branch are you commiting to?
