### ISSUE TITLE
Inari UI

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#64]
**Operational Preface:**

Open a new branch from **Canary** when ready for review open a PR against **Canary**. Branch should be titled Inari and mention this issue
Similar implementation can be found at: https://app.sushi.com/saave 
Similar current page directory can be found at: https://github.com/sushiswap/sushiswap-interface/tree/master/src/pages/Saave

_When submitting the PR please open a new folder under src/pages titled Inari and co-locate any relevant components within this folder as well._ 

----------------------------------------
**(More details to follow ...)** 

Use components you feel are appropriate to integrate to the following contract hooks:
https://etherscan.io/address/0xd4c7EF086361C2beC6718D5B6E82EE32eb1E050e#code

While the UI for this is not opinionated, this implementation is expected to be fully functional and tested when submitted for PR. Please also track and submit the appropriate gas fees expended for testing.

Additionally you will need to update routing to reflect localhost:3000/inari for the relevant screens found in the figma above. You do not need to implement the header as this exists currently on the master branch

**Comment by msilucifer** [comment]
In ```canary``` branch, I can't find ```saave``` page.  But in ```master``` branch, there is ```saave``` page.
Should I implement ```inari``` contract in ```canary``` branch regardless of this?
