### ISSUE TITLE
Portfolio page doesn't querry by the url address param

### ISSUE THREAD

**Issue by gasperbr** [sushiswap/sushiswap-interface#693]
https://app.sushi.com/portfolio/:address doesn't actually query the provided address balances but it tried to fetch the connected wallet balances.

**Comment by gasperbr** [comment]
Hmm check https://polygon.sushi.com/account/0x850a57630A2012B2494779fBc86bBc24F2a7baeF for example. Its our polygon multisig which has a couple of millions sitting in the wallet but its not showing up. Might be some other issue though

**Comment by chillichelli** [comment]
Alright, this is helpful. Gonna debug
