### ISSUE TITLE
Smarter Percentage Input

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#83]
<img width="647" alt="PercentageInput" src="https://user-images.githubusercontent.com/70670294/117171525-8ef13380-ad90-11eb-99ee-d0772b0949c6.png">

https://github.com/sushiswap/sushiswap-interface/blob/master/src/components/PercentInputPanel/index.tsx#L18

The Percentage InputPanel could be a little smarter and prevent users from typing over 100. Could potentially also add some helper buttons to preselect percentages similar to slippage selectors:

<img width="318" alt="slippage" src="https://user-images.githubusercontent.com/70670294/117171950-f3ac8e00-ad90-11eb-9390-09a40c030720.png">

https://github.com/sushiswap/sushiswap-interface/blob/master/src/components/TransactionSettings/index.tsx#L154

**Comment by ironsoul0** [comment]
I would love to help with this one
