### ISSUE TITLE
It shows wrong rate

### ISSUE THREAD

**Issue by sarangparikh22** [sushiswap/sushiswap-interface#862]
[![Screenshot_2022-07-14_19-33-32.png](https://mrkr.io/s/62d06f8c7295a3a82991b89b/2)](https://mrkr.io/s/62d06f8c7295a3a82991b89b/0)

Steps to reproduce:
Create limit order with below market price.

Actual result:
It shows that it is above the market rate.

Expected result:
It should show that it is below the market rate.

---

**Source URL:** [https://app.sushi.com/limit-order?chainId=43114](https://app.sushi.com/limit-order?chainId=43114)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d06f8c7295a3a82991b8ee_d1dcd31fbd3e76a2)

**Console:** [ℹ️  2 info 📃  78 logs ](https://app.marker.io/i/62d06f8c7295a3a82991b8ee_d1dcd31fbd3e76a2?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Linux 5.11.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 984</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by sarangparikh22** [comment]
[![Screenshot_2022-07-14_19-33-48.png](https://mrkr.io/s/62d06f9c447e86beaf1d772f/2)](https://mrkr.io/s/62d06f9c447e86beaf1d772f/0)

**Comment by sarangparikh22** [comment]
The review the limit order shows the correct value.

**Comment by matthewlilley** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d06f8c7295a3a82991b8ee_d1dcd31fbd3e76a2) - This issue was marked as resolved in Marker.io.
