### ISSUE TITLE
Mockup: xSUSHI Use Cases Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#87]
Operational Preface:

Open a new branch when ready for review open a PR against Master. Branch should be titled mockup_xsushi_uses and mention this issue

When submitting the PR please add components to the existing src/pages/SushiBar folder and co-locate any relevant components within this folder as well.

Sample Design Page:

<img width="612" alt="MoreXSushi" src="https://user-images.githubusercontent.com/70670294/117237105-d1962880-adef-11eb-839f-e7304b140e6c.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/zibFzATC7X8UEdkGMRPllo/Staking?node-id=121%3A1905. If you are unable to access the Figma please reply in issue with an email address. 

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are not expected to integrate with any existing web3 hooks or external apis.

Additionally you will need to update routing to reflect localhost:3000/sushibar/tips for the relevant screen found in the figma above. You do not need to implement the header as this exists currently on the project

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by ironsoul0** [comment]
Please see #92
