### ISSUE TITLE
Style Improvements to Migration Page

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#89]
**Operational Preface:**

Open a new branch when ready for review open a PR against **Master**. Branch should be titled **migration_update** and mention this issue. _Once self-assigned an update is expected within 1 day or the issue is at risk of being assigned by a new claimant._

When submitting the PR please add components to the existing src/pages/Migrate folder and co-locate any relevant components within this folder as well. The existing implementation currently resides in https://github.com/sushiswap/sushiswap-interface/blob/master/src/pages/Migrate/index.tsx

You can experience the migration feature here: https://app.sushi.com/migrate

**Description:**

Currently the Migrate Page has various states that expand the component as the user progresses through. 

<img width="642" alt="Migrate" src="https://user-images.githubusercontent.com/70670294/117238749-153e6180-adf3-11eb-896e-fd90af5e6dff.png">

However this pattern does not signal to the user what may be upcoming and may discourage users from starting. An enhancement to this component would be to display all sections and display the actionable components once previous states have been resolved.

<img width="359" alt="Screen Shot 2021-05-05 at 10 44 48 PM" src="https://user-images.githubusercontent.com/70670294/117239003-9138a980-adf3-11eb-930a-57d2e1ad5137.png">

Implement the following improvements based on the suggestions above. This issue is for delivering a responsive mockup and maintain the existing functionality of Migrate.

Should you need access to new colors you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by ironsoul0** [comment]
Please see #91
