### ISSUE TITLE
Restyle PoolFinder

### ISSUE THREAD

**Issue by omakasebar** [sushiswap/sushiswap-interface#90]
Operational Preface:

Open a new branch when ready for review open a PR against Master. Branch should be titled **restyle_poolFinder** and mention this issue.

When submitting the PR please add components to the existing src/pages/PoolFinder folder and co-locate any relevant components within this folder as well. An existing implementation can be found here: https://github.com/sushiswap/sushiswap-interface/tree/master/src/pages/PoolFinder

You can experience this feature at: https://app.sushi.com/find

Sample Design Page:

<img width="749" alt="PoolFinder" src="https://user-images.githubusercontent.com/70670294/117239524-90544780-adf4-11eb-87ad-d5a69932f2ca.png">

More design details and assets can be found on Figma Dashboard: https://www.figma.com/file/yWJykiIb4TkV6zbLpItPDv/Exchange?node-id=70%3A67. If you are unable to access the Figma please reply in issue with an email address.

Implement the following pages based on the design above. This issue is for delivering a responsive mockup and you are expected to maintain the existing functionality of the PoolFinder component.

You do not need to implement the header as this exists currently on the project

Should you need access to new colors in the Figma prototype you can add those colors to the tailwinds configuration file here: https://github.com/sushiswap/sushiswap-interface/blob/master/tailwind.config.js#L23

**Comment by TopETH** [comment]
I'm working on this issue now.

**Comment by omakasebar** [comment]
Resolved in https://github.com/sushiswap/sushiswap-interface/pull/123
